### ISSUE TITLE
custom fonts always appear italic in preview / book view

### ISSUE THREAD

**Issue by taikuli** [Sigil-Ebook/Sigil#144]
If CSS is

```css
@font-face {
	font-family:"OCRA";
	font-style:normal;
	font-weight:normal;
	src : url("../Fonts/OCRAStd.otf");
}
```
any text using OCRA as font-family will be rendered as italic in v 0.8.901.
This happens for all fonts (tried three different up to now).

**Comment by dougmassay** [comment]
Are you certain there's not something else in play here? I have several books with embedded fonts--none of which render as italic (unless requested to do so) using v0.8.901.

What O.S. are you using?

**Comment by taikuli** [comment]
Yes, I'm quite certain. :-)
See yourself...
Hm. ePub is not a supported filetype, so I can only give you a screenshot. :-(
![screenshot](https://cloud.githubusercontent.com/assets/15313608/10717520/2e2caa92-7b5b-11e5-944d-245b6962263a.png)
I'm using Windows 10 (Build 10565).
This is the CSS
```CSS
@font-face {
    font-family:"OCRA";
    font-style:normal;
    font-weight:normal;
    src: url("../Fonts/OCRAStd.otf");
}

p {
	font-family: "OCRA", serif;
}
```
And this is the HTML
```HTML
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
  <link href="../Styles/Style0001.css" rel="stylesheet" type="text/css"/>
</head>

<body>
  <p>
  The quick brown fox jumps over the lazy dog.
</p>
</body>
</html>
```
And the rest is the default from Sigil 0.8.901.
