### ISSUE TITLE
"Restructure Epub to Sigil Norm" changes values in quotation marks

### ISSUE THREAD

**Issue by richilton** [Sigil-Ebook/Sigil#592]
Open an ePub containing a CSS file that is **not** in a folder called `Styles`, and select `Tools > Restructure Epub to Sigil Norm`. Any CSS values in quotation marks will be URL-encoded and prefixed with `"../[name of original CSS folder]"`.

For example, the following CSS is changed from...
```
div {
	content: "this is a test string!";
}
```
...to...
```
div {
	content: "../css/this%20is%20a%20test%20string%21";
}
```
A [minimal example](https://github.com/Sigil-Ebook/Sigil/files/6024677/Test.zip) is attached (renamed to .zip so GitHub would allow the upload!).

Sigil version: `1.4.3`
Loaded Qt: `5.12.9`
Platform: Windows 10

**Comment by dougmassay** [comment]
All quoted strings? Or just quoted strings that are part of a content attribute's value.

**Comment by kevinhendricks** [comment]
Hopefully the latter.  We will need to narrow down our css updates regular expressions we use to try to detect this case.

**Comment by kevinhendricks** [comment]
Also we may want to consider incorporating our new css parser into this regular expression css updating process to help rule out things we should not touch.  It might help.

**Comment by kevinhendricks** [comment]
Looking at PerformCSSUpdates because of @import we support updating  paths  in quotes as @import can use a path in quotes instead of the url() function.  We also look for url() as part of content: but because of what we do for @import we are catching things in quotes following content: incorrectly.


One solution is to handle @import with just a quoted path separately.

Thoughts?

**Comment by richilton** [comment]
> All quoted strings? Or just quoted strings that are part of a content attribute's value.

It appears to be selective. 
```css
div {
	content: "Test String";
	background-image: url("Test String");
	background-image: url('Test String');
	cursor: url("Test String");
	quotes: "“" "”" "‘" "’";
	font-family: "Test String";
	invalid-property: url("Test String");
	margin: "Test String";
	"Test String";
}
```
...becomes...
```css
div {
	content: "../css/Test%20String";
	background-image: url("../css/Test%20String");
	background-image: url('../css/Test%20String');
	cursor: url("Test String");
	quotes: "“" "”" "‘" "’";
	font-family: "Test String";
	invalid-property: url("Test String");
	margin: "Test String";
	"Test String";
}
```
